### ISSUE TITLE
RFC: Changes to the configuration format to further standardize it

### ISSUE THREAD

**Issue by Noki** [freifunk-berlin/bbb-configs#751]
I talked with @FFHener about ways to further standardize the configuration format. We came up with the following ideas:

- Add model files for non OpenWRT devices (ubiquiti antennas, switches, webcams, ...)
- Add all non OpenWRT devices as hosts alongside the OpenWRT devices
- Add configurations values to individual non OpenWRT hosts (e.g. height+altitude, alignment, ssid, ...)

Doing so will allow us to move some parts of the configuration into the new model files:

- SNMP profiles
- airOS DFS reset (default configuration, with configuration overrides for each host)

In addition this will allow us to:

- derive a proper documentation for each location that could be used to update the wiki / website
- generate configuration files for non OpenWRT devices when building the location

Here are examples of how a model file for a non OpenWRT device could look like:

```
brand_nice: Ubiquiti
model_nice: Wave Long-Range

wireless_devices:
  - name: 11ad_standard
    band: 60g
  - name: 11a_standard
    band: 5g
    htmode_prefix: HE

snmp_profile: af60
```

```
brand_nice: Ubiquiti
model_nice: Nanostation 5AC

wireless_devices:
  - name: 11a_standard
    band: 5g
    htmode_prefix: HE

snmp_profile: airos_8

airos_dfs_reset:
  - username: "ubnt"
    password: "file:/root/pwd"
    daytime_limit: "2-7"
```

The host configuration for such an device could look like this:

```
hosts:
  - hostname: q216-tierpark
    role: ptp-ap
    ptp: true
    model: "ubnt_nanobeam_5ac-gen2"
    height: 15
    altitude: 54
    orientation: ost
    ssid: "q216-tierpark" #to override default ssid (freifunk-{location}-{orientation}-{frequency} / freifunk-{location}-{orientation})
    channel: 128
    channel-width: 40
    username: "root" # to override the default ("ubnt")
    password: "file:/root/tierpark-pwd.txt" # to override the default ("file:/root/pwd.txt)
    daytime_limit: "4-5"  # to override the default ("2-7")
```

We want to discuss this at the community day. Please let us know about any thoughs you have on this.
