### ISSUE TITLE
uplink: allow multiple uplink roles

### ISSUE THREAD

**Issue by noxilixon** [freifunk-berlin/bbb-configs#806]
Right now I could only use one uplink via tunnel. It would be nice if I could set multiple uplinks that each create a tunnel.

**Comment by noxilixon** [comment]
Das matching von tunnel-interfaces und uplink-interface im `tunspace.j2` template wird gerade über `role: uplink` gemacht, wir könnten stattdessen namen vergeben. z.b.

```
networks:
  - vid: 50
    role: uplink
    name: uplinkeins
  - role: tunnel
    uplink: uplinkeins
    ifname: ts_wg0
    # ...
  - vid: 51
    role: uplink
    name: uplinkzwei
  - role: tunnel
    uplink: uplinkzwei
    ifname: ts_wg1
    # ...
```
Und in `tunspace.j2` das matching ändern.
